name: AdvRes
main: cc.isotopestudio.advres.AdvRes
depend: [Residence]
author: Mars
description: AdvRes
website: http://isotopestudio.cc
version: 1.3.0

commands:
  advres:
    description: AdvRes
    usage: /<command>